name: url_loader
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.6
  url_launcher: ^6.1.12
  webview_flutter: ^2.1.0
  # ...other dependencies


  # ...other dependencies


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

